<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [62]:
x=-10
assert x>=0, "x is becoming negative!"
print(x)

# x=-10
# AssertionError: x is becoming negative!

AssertionError: x is becoming negative!

### 1.2 try-except

In [7]:
number=input("Give me a number and I will calculate its square.")
# input lets the user enter something to be used in a function
square=int(number)**2
# int to convert string to integer for calculation
print(f'The square of {number} is {square}!')


Give me a number and I will calculate its square.7
The square of 7 is 49!


In [10]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")
# instead of giving an error, python will ignore it and run the except block

Give me a number and I will calculate its square.pants
Oh oh! I cannot square pants!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [16]:
def funny_add(a,b,c=1):
    return a+10*b+100*c

print(funny_add(1,2))
print(funny_add(1,2,3))
# 1+20+300=321
print(funny_add(a=1,b=2))
print(funny_add(c=3,b=1,a=2))
print(funny_add(1,c=3,b=2))
funny_add(1,b=2)

# funny_add(a=2, 1) will not work. keyword cannot be followed by positional

121
321
121
312
321


121

### 2.2 Docstrings

In [13]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c
# write our own help guide

help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [31]:
def my_function(angle, trig_function):
    return trig_function(angle)

print(my_function(np.pi/2,np.sin))
# sin(pi/2)=1
print(my_function(np.pi/2,np.cos))

my_function(np.pi/2,lambda x:np.cos(2*x))
# anonymous function required to prevent an error from cos(2*x)

1.0
6.123233995736766e-17


-1.0

### 2.4 More unpacking

In [42]:
x,y,z=[1,2,3]
print(x,y,z)
x,y,z=np.array([1,2,3])
print(x,y,z)

x,*y,z=np.array([1,2,3,4,5])
print(x,y,z)
# *y means to create a sublist within the list/array

x,*_,y=[1,2,3,4,5]
print(x,y)
# _ is a dummy variable just like a b c etc, but by convention it means youre going to ignore it
# print(x,_,y) also gives 1 [2,3,4] 5


1 2 3
1 2 3
1 [2, 3, 4] 5
1 5


## Exercise 1 :  A better calculator I

In [10]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 0, 56, 24, 73])

def add(x,y):
    return x+y
print(add(x,y))

def subtract(x,y):
    return x-y
print(subtract(x,y))

def multiply(x,y):
    return x*y
print(multiply(x,y))

def divide(x,y):
    assert np.all(y!=0), "division by zero is undefined!"
    return x/y
print(divide(x,y))


# Your solution here




[100  34 100 100 100]
[-28  34 -12  52 -46]
[2304    0 2464 1824 1971]


AssertionError: division by zero is undefined!

## Exercise 2 :  A better calculator II

In [36]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 0, 56, 24, 73])
def divide(x,y):
     return x/y

try:
    assert np.all(y!=0)
except:
    print("you have encountered assertion error")

# with current knowledge, using assert under try is the only way, though redundant
# without assert, numpy is (according to yuan zhe) too smart and does not have zerodivisionerror
# it evaluates division by 0 as infinity, which results in runtime warning but is NOT an error
# therefore the try still passes and except does not occur


you have encountered assertion error


In [24]:
try:
    print(a)
except:
    print('yeah no')

yeah no
