<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [5]:
def greeting(name):
    if name=='Batman':
        return 'Hello Batman! So nice to meet you!'
    else:
        return f'Hello {name}!'

print(greeting('Superman'))
greeting('Batman')
# the new function greeting() only accepts the name argument

Hello Superman!


'Hello Batman! So nice to meet you!'

In [10]:
greet=greeting('Superman')
greet

'Hello Superman!'

In [54]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
print(list_min)

1


### 1.2 Named functions that don’t return

In [ ]:

# Your code here


### 1.3 Anonymous functions

In [2]:
my_short_function=lambda name:f"Hello {name}!"
my_short_function(name="Superman")


'Hello Superman!'

In [56]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)
# sorted according to a default key (considering the first element)

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [15]:
sorted(numbers, key=lambda x:x[1])
# sort by comparing a custom key using the second element of the sub-lists

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [17]:
sorted(numbers, key=lambda x:sum(x))
# sorted by increasing sum of the elements in a sub list

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [22]:
def greeting(name='no one'):
    if name=='Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting()


'Hello no one!'

In [29]:
print('I','am','Batman!')
print('I','am','Batman!',sep='---')
#insert a string '---' between values

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

## Exercise 1 :  Do you know why?

In [69]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        print(f'Hello {name}!')
x=greeting('superman')
print(x)

Hello superman!
None


In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

x=greeting('superman')
print(x)

Hello superman!


`def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'`

the second return ends the function and provides an output, which is similar to else

## Exercise 2 :  Calculator functions

In [2]:
import numpy as np

In [3]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 0, 56, 24, 73])

def add(x,y):
    return x+y
print(add(x,y))

def subtract(x,y):
    return x-y
print(subtract(x,y))

def multiply(x,y):
    return x*y
print(multiply(x,y))

def divide(x,y):
    if 0 in y:
        print('zero')    # print zero
        #exit()            then the kernel dies - why do i need this
    else:
        return x/y
divide(x,y)


[100  34 100 100 100]
[-28  34 -12  52 -46]
[2304    0 2464 1824 1971]
zero


## Exercise 3 :  max_info() with NumPy

In [20]:
numbers=np.array([40, 27, 83, 44, 74, 51, 76, 77, 10, 49])

def max_info(numbers):
    return (np.max(numbers),np.argmax(numbers))
    
max_info(numbers)


(83, 2)