<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x=py_list
# works for both lists and arrays


'a1'

In [16]:
print(x[0])
print(x[-1])
print(x[0:3])
# index from elements 0 to 2 (3 elements)
print(x[1:6])
# index from elements 1 to 5 (6-1=5 elements)
print(x[1:6:2])
# index every 2nd element from 1 to 5
print(x[5:])
print(x[:5])
# index from element 5 to the end and from the first element to the 5th
print(x[5:2:-1])
# index in reverse from element 5 to 3 (does not work without :-1)
print(x[::-1])
# need double colon :: or else the reversing doesnt work


a1
j10
['a1', 'b2', 'c3']
['b2', 'c3', 'd4', 'e5', 'f6']
['b2', 'd4', 'f6']
['f6', 'g7', 'h8', 'i9', 'j10']
['a1', 'b2', 'c3', 'd4', 'e5']
['f6', 'e5', 'd4']
['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']


### 1.2 Subsetting by masking (Arrays only)

In [20]:
np_array=np.array([1,2,3,4,5,6,7,8,9,10])
my_mask=np_array>3

print(my_mask)
# tells you which elements are more than 3

print(np_array[my_mask])
# only shows those elements that are true

np_array[np_array>3]
# no need create new variable

[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]


array([ 4,  5,  6,  7,  8,  9, 10])

In [27]:
print(np_array[~(np_array>3)])
# ~ acts as NOT, so show all elements NOT more than 3

print(np_array[(np_array>3)&(np_array<8)])
# & means AND

print(np_array[(np_array<3)|(np_array>8)])
# | means OR, so all elements that fulfill one or both requirements will appear


[1 2 3]
[4 5 6 7]
[ 1  2  9 10]


### 1.3 Indexing & Slicing 2D Lists

In [33]:
py_list_2d=[[1, "A"], [2, "B"], [3, "C"], [4, "D"],
            [5, "E"], [6, "F"], [7, "G"], [8, "H"],
            [9, "I"], [10, "J"]]

print(py_list_2d[3])
# all elements in the 4th brackets (position 3 starting from 0)
print(py_list_2d[3][0])
# first element in 4th position
print(py_list_2d[:3])
# index from 0 to 3
py_list_2d[:3][0]
# gives the first from py_list_2d[:3]

[4, 'D']
4
[[1, 'A'], [2, 'B'], [3, 'C']]


[1, 'A']

### 1.4 Indexing & Slicing 2D Arrays

In [42]:
np_array_2d=np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                    [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                    [9, "I"], [10, "J"]])

print(np_array_2d[3])
print(np_array_2d[3,0])
# np_array_2d[3][0] works too
print(np_array_2d[:3])
print(np_array_2d[:3,0])
# gives the first element of each sub-array from the first to third sub-array
print(np_array_2d[3:6,0])
# first element from sub-arrays 4 to 6
np_array_2d[:,0]
#first element from all : the sub arrays


['4' 'D']
4
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]
['1' '2' '3']
['4' '5' '6']


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [44]:
x=[1]*10
x
# grow the entire list [1] 10 times

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [50]:
x=[1]
x=x+[2]
x=x+[3]
x=x+[4]
print(x)
# combines the lists together into one list

x=[1]
x+=[2]
x+=[3]
x+=[4]
x
# alternate way of typing

[1, 2, 3, 4]


[1, 2, 3, 4]

In [58]:
x=[1]
x+=[2,3,4]
print(x)
#combines the lists

x=[1]
x=x+[2,3,4]
print(x)
# same thing

x=[2]
x=x+[1,3,4]
x
# combines in order

[1, 2, 3, 4]
[1, 2, 3, 4]


[2, 1, 3, 4]

In [61]:
x=[1]
x=[2,3,4]+x
x
# adds the new list to the front of the first list

[2, 3, 4, 1]

## 2 Some loose ends

### 2.1 Tuples

In [ ]:

# Your code here


### 2.2 Be VERY careful when copying

In [ ]:

# Your code here


## Exercise 1 :  Total recall?

In [ ]:



# Your solution here




## Exercise 2 :  Show me the ‘odd’ letters

In [ ]:



# Your solution here


