<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [6]:
py_super_names=['Black Widow','Iron Man','Doctor Strange']
py_real_names=['Natasha Romanoff','Tony Stark','Stephen Strange']
# python lists aka lists

np_super_names=np.array(['Black Widow','Iron Man','Doctor Strange'])
np_real_names=np.array(['Natasha Romanoff','Tony Stark','Stephen Strange'])
# numpy arrays aka arrays

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"}
# dictionary, uses a key-value structure ('Natasha Romanoff' and 'Black Widow' are associated) 


### 1.2 Accessing data from a list (or array)

In [11]:
print(py_real_names[0])
print(np_super_names[2])

# python starts counting at zero

Natasha Romanoff
Doctor Strange


In [19]:
print(py_real_names[-1])
# counts from the back of the list (last element)

print(py_real_names[-2])
# second last element in the list

print(np_super_names[-1])

Stephen Strange
Tony Stark
Doctor Strange


### 1.3 Accessing data from a dictionary

In [25]:
print(superhero_info['Natasha Romanoff'])

# print(superhero_info['Black Widow']) does not work as you can only print the value (black widow) using the key (natasha romanoff) and not the other way around

Black Widow


### 1.4 Higher dimensional lists

In [33]:
py_superhero_info=[['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# double square brackets - list within a list - 2D list
# if use ([]), it becomes a list within a tuple

## 2 Lists vs. Arrays

### 2.1 Size

In [3]:
py_list_2d=[[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d=np.array(py_list_2d)
# create a new array based on the list above and name it np_array_2d

len(py_list_2d)
# number of elements in the list

print(np_array_2d)
np_array_2d.shape
# shape is an attribute of the numpy array, not a function

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]


(10, 2)

### 2.2 Arrays are fussy about type

In [8]:
py_list=[1,1.5,'A']
np.array(py_list)
# '' denotes that the numbers are now in english
# numpy array only tolerates one data type (numbers or letters)


array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [13]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)
# _ is for naming, . is for attribute (actually does something)

np_array+10
# py_list+10 does not work, cannot add numbers to lists

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [16]:
py_list_1=[1,2,3,4,5]
py_list_2=[10,20,30,40,50]

np_array_1=np.array(py_list_1)
np_array_2=np.array(py_list_2)

[10 20 30 40 50]


In [21]:
print(py_list_1+py_list_2)
# adding LISTS together combines all the elements into one list

np_array_1+np_array_2
# adding ARRAYS together adds up the values of each element based on their positions

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


array([11, 22, 33, 44, 55])

In [25]:
py_list_1+np_array_1
# works somehow


array([ 2,  4,  6,  8, 10])

### 2.5 Multiplying by a Number

In [33]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

print(py_list*2)
# makes the list longer by repeating it
# only works for integers, no float (decimals)

np_array*.5
# multiplies each element in the array by the number
# can be multiplied by decimal values

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([0.5, 1. , 1.5, 2. , 2.5])

In [38]:
# py_list*py_list doesnt work because py_list is not an integer

print(np_array*np_array)
# can multiply arrays together, each element is multiplied by the element in the corresponding position of the other array

print(py_list*np_array)
# list can multiply by array

np_array_2=np.array([0.5,1.5,2.5,3.5,4.5])
py_list*np_array_2
# list can be multiplied by array even when array has non integers


[ 1  4  9 16 25]
[ 1  4  9 16 25]


array([ 0.5,  3. ,  7.5, 14. , 22.5])

### 2.6 Squaring

In [42]:
# py_list**2 does not work

np_array**2
# square each element in the array
# can cube (**3) as well


array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [51]:
py_list==3
# works but doesnt make much sense
# py_list>3 just does not work

print(np_array==3)
# checks if 3 is equivalent to each element in the array

np_array>3
# checks if each element in the array is larger than 3

[False False  True False False]


array([False, False, False,  True,  True])

### 2.8 Mathematics

In [58]:
print(sum(py_list))
# adds up the elements in the list
# py_list.sum() will not work

py_list_1=[1,5,2,3,4]
print(max(py_list_1))
# gives the largest value regardless of order

min(py_list_1)

15
5


1

In [67]:
print(sum(np_array))
print(np_array.sum())
# both ways work for arrays

print(np_array.mean())

print(np_array.max())

np_array.min()


15
15
3.0
5


1

## Exercise 1 :  Total recall?

Two similarities between lists and arrays.
    - Both lists and arrays can undergo addition and multiplication
    - Both lists and arrays can be 2D
    
Two differences between lists and arrays.
    - Lists cannot be squared while arrays can be squared
    - Lists can have more than one data type (eg. english and numbers) while arrays can only have one data type (if numbers and english are both present, numbers will be converted to english)
    - Lists use square brackets [] while arrays use round brackets _and square brackets ([])_
   
What is a dictionary?
       A dictionary has a key and a value associated with it, _separated by a colon :_. The value can be called using the key but not the other way around _(dictionary format is {'key1':'value1','key2','value2'})_
       


## Exercise 2 :  Index me

In [73]:
py_list=['a1','b2','c3','d4','e5','f6','g7','h8','i9','j10']

print(py_list[0])
print(py_list[2])
print(py_list[4])
print(py_list[6])
print(py_list[8])
# is there a way to print all the necessary elements together with one print function?


a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [77]:
superhero_info={"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Natasha Romanoff']=superhero_info['Natasha Romanoff'].upper()
superhero_info['Tony Stark']=superhero_info['Tony Stark'].upper()    
superhero_info['Stephen Strange']=superhero_info['Stephen Strange'].upper()

print(superhero_info['Natasha Romanoff'])
print(superhero_info['Tony Stark'])
print(superhero_info['Stephen Strange'])



BLACK WIDOW
IRON MAN
DOCTOR STRANGE


## Exercise 4 :  How many ones

In [16]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

np_numbers_array=np.array(numbers)

np_numbers_array==1
print(sum([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False]))

# since sum() considers True to be 1, there are 9 True and therefore 9 1s


np_numbers_array[np_numbers_array==1]
# masking to show only 1s

9


array([1, 1, 1, 1, 1, 1, 1, 1, 1])